### ISSUE TITLE
Handling component states

### ISSUE THREAD

**Issue by jacojoubert** [prototypal-io/untitled-ui#16]
Currently we have a lot of this kind of stuff in templates:

```
{{if states.active 'active'}}
{{if states.focus 'focus'}}
{{if states.disabled 'disabled'}}
{{if states.loading 'loading'}}"
```

At a minimum, it'd be nice to reduce this to:

```
<button {{ui-root}}>
  <div class="wrapper" {{ui-state 'active'}}>
    <div class="label {{ui-state 'active' 'loading'}}>
      {{yield}}
    </div>
  </div>
</button>
```

It'd also be nice to be able to somehow remove this boilerplate all together, but unsure how that'd work.
### Current issues with how the active state works
- Having another transition on a button causes it to change state.
- Switching z-index on the element causes it to change state (necessary for button group)
### Tasks
- [x] Helper for setting `states`
- [ ] Helper for setting `classes`
- [ ] `{{ui-root}}`

**Comment by jacojoubert** [comment]
This should also fix where we have to use `concat` to assign multiple classes to inputs. See https://github.com/prototypal-io/untitled-ui/blob/master/addon/templates/components/ui-input--default.hbs#L11-L15

**Comment by ebryn** [comment]
Broke the remaining tasks out into separate issues
