### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by jacojoubert** [prototypal-io/untitled-ui#17]
## Proposed API

``` hbs
{{#ui-table data=data sortBy=sortBy as |table|}}
  {{#table.rowLayout as |layout|}}
    {{#layout.column label="ID" flex=1}}
      {{layout.data.id}}
    {{/layout.column}}

    {{#layout.column label="Name" flex=4 sortable=true}}
      {{layout.data.name}}
    {{/layout.column}}

    {{#layout.column label="Email" flex=6 sortable=true}}
      {{layout.data.email}}
    {{/layout.column}}
  {{/table.rowLayout}}

  {{#table.rowLayout breakpoint=800 as |layout|}}
    {{#layout.column label="Name" flex=4 sortable=true}}
      {{layout.data.name}} <br />
      {{layout.data.id}}
    {{/layout.column}}

    {{#layout.column label="Email" flex=6 sortable=true}}
      {{layout.data.email}}
    {{/layout.column}}
  {{/table.rowLayout}}
{{/ui-table}}
```
# Issues
- Requires access to the yielded block which is not currently supported in ember.

**Comment by jacojoubert** [comment]
Some comments on the implementation from #64 
- We should delete the old `ui-table` and rename `ui-tablo`
- Unless I am mistaken on how this currently works, I think the `ui-table--column` as an actual component is unnecessary and serves no function. It should be removed.
- We should only create `kind` components the implement aesthetic styles. Components that implement the API of `table` should not be a `kind`. So I think we should rename `ui-table--default-layout` to remove the `default` designation. 
- `row` and `cell` components need a way to know if they are a header row/cell.
- We use `flex` as the way to specify size, but i think it should be renamed to `size`, and it should require a hash of `min`, `max`, and `flex`, with only flex required.
- Columns should not require a `name` property. It is desirable to sometimes not have a label for a column.
- Columns need to have a way to know which of the data fields they should sort by. So instead of having a `sortable` option, I think instead we should have `sort-by` and the user can assign the path that should be sorted on. If it is absent then the column is not sortable.

**Comment by HeroicEric** [comment]
@jacojoubert Thanks for the thorough review 😄 

> We should delete the old ui-table and rename ui-tablo

👍 

> Unless I am mistaken on how this currently works, I think the ui-table--column as an actual component is unnecessary and serves no function. It should be removed.

👍 It is never invoked because the transform replaces it with `ui-table-row` and `ui-table-cells`

> We should only create kind components the implement aesthetic styles. Components that implement the API of table should not be a kind. So I think we should rename `ui-table--default-layout` to remove the default designation.

I'm not sure what you mean.

> row and cell components need a way to know if they are a header row/cell.

👍  It should be pretty easy to use a different kind for the headers row/cells. [Here's the part of the transform that we'd want to update](https://github.com/prototypal-io/untitled-ui/blob/master/lib/plugins/transform-ui-table-components.js#L71-L76). I think we could either yield a `table.headerRow` or maybe pass a value for the kind.

> We use flex as the way to specify size, but i think it should be renamed to size, and it should require a hash of min, max, and flex, with only flex required.

Should be doable. We'll probably want something similar for the layouts.

> Columns should not require a name property. It is desirable to sometimes not have a label for a column.

This should also be doable. The way that it currently works, we'll need some way to identify the layouts to switch between which one are active, but we could generate something unique.

**Comment by jacojoubert** [comment]
> I'm not sure what you mean. 

`ui-table--default-layout` doesn't have any styling information in it. It exists only to render the appropriate content. Thus, to create a new `kind` the user shouldn't have to create a new `layout` component. It should be called `ui-table-layout` and be used for all table kinds.

**Comment by ebryn** [comment]
First pass (#64) was merged.
