### ISSUE TITLE
Block List

### ISSUE THREAD

**Issue by HeroicEric** [prototypal-io/untitled-ui#31]
<img width="419" alt="screen shot 2016-06-13 at 11 23 00 am" src="https://cloud.githubusercontent.com/assets/602204/16012855/3ae97864-3159-11e6-8ea1-b6611fcc5f46.png">
#### Examples

http://ionicframework.com/docs/v2/components/#icon-list
http://foundation.zurb.com/apps/docs/#!/block-list
http://getbootstrap.com/components/#list-group
## Proposed API

``` hbs
{{#ui-block-list as |list|}}
  {{#list.item}}Red{{/list.item}}
  {{#list.item}}Yellow{{/list.item}}
  {{#list.item}}Blue{{/list.item}}
{{/ui-block-list}}
```
### ui-block-list-item states
- `active`
- `disabled`
- `hover`
# Questions
- Is this wanted?
- Should this actually just be more a generic `{{ui-list}}` and `{{ui-list--block}}` can a **kind**?

**Comment by jacojoubert** [comment]
I this would be useful, and specifically I can think of one project I would have used it in a mobile context. I think it would be better to call it simply `ui-list`. I don't think `block` adds any value to the name. I can see an `iOS` kind as well as a more generic one.

Should we support large lists via this component? If I wanted to show 300 people in a list on a mobile device would this component remain performant? If that is a use case we should allow the user to pass in the full list and have the component iterate over the list internally. Though for short lists the proposed API is nicer.
