### ISSUE TITLE
Base component

### ISSUE THREAD

**Issue by HeroicEric** [prototypal-io/untitled-ui#33]
## Overview

I think it might make sense to create a base component that we can extend from to remove some of the boilerplate that exists between all of our UI components. This issue is for discussing what this might look like.

Things that are common between every UI component:
- `tagName` set to `''`
- `kind` defaults to `default`
- `size`
- `frame`: a computed prop that determines which component to render, based on the `kind`
- `classes` this one seems to be the most complicated to extract since it does currently do some things differently across the different components.
- `states`
### Classes & States

`classes` and `states` properties are definitely more complicated than `kind` and the others. Currently, ui components define something like this:

``` js
classes: Ember.computed('size', function() {
  return {
    size: `ui-font-size--${this.get('size')}`,
    class: this.get('class')
  }
}),

states: Ember.computed('isDisabled', 'loading', 'active', 'browserActive', 'focus', function() {
  return {
    disabled: this.get('isDisabled'),
    loading: this.get('loading'),
    active: this.get('browserActive') || this.get('active'),
    focus: this.get('focus')
  }
})
```
- What could a DSL for extending this look like?
- Is there a default set of class/props we would want to automatically handle?
### Generator

Once we have a base component, we could create a generator to help generate new components that extend from the base ui component.

``` bash
$ ember g ui-component ui-list
  create addon/components/ui-list.js
  create addon/templates/components/ui-list.hbs
  create addon/styles/components/ui-list.scss
  create tests/integration/components/ui-list-test.js
  create app/components/ui-list.js
```

Generated component example:

``` js
import UIComponent from './ui-component';
import layout from '../templates/components/ui-list';

export default UIComponent.extend({
  layout
});
```

**Comment by ianstarz** [comment]
Seems like nice ergonomics. This combined with the auto generating for non-default components will make it easy to implement "scss-only" components. In the case that a component doesn't have an associated "default" component (i.e. `ui-button--base` and there is no `ui-button--default`) the generated component could simply export a subclass of this base component.

What would the `ui-component` template boilerplate be? Just `{{yield}}`?

**Comment by HeroicEric** [comment]
@ianstarz That brings up an interesting point. There are actually two different kinds of components that we're using. We've got base UI components that basically just delegate to a "kind" and the "kind" components themselves.

Base ui component template example:

``` hbs
{{#component frame
  classes=classes
  kind=kind
  size=size as |component|}}
    {{yield component}}
{{/component}}
```

Kind ui component template example:

``` hbs
<div class=":component {{classes.size}}">
  <div class="wrapper">
    {{yield (hash
      titlebar=(component "ui-panel--default-titlebar")
      content=(component "ui-panel--default-content"))}}
  </div>
</div>
```

All of the stuff in the original post had the base UI components in mind. I think it might make sense to have two base classes/generators.

The default template for the **kind** component would probably be something like:

``` hbs
<div class=":component {{classes.size}}">
  {{yield}}
</div>
```

**Comment by jacojoubert** [comment]
Just to clarify, `ui-button--base.scss` isn't a kind itself, it is just a set of reset styles that generally every `kind` will most likely need to import. It should maybe be renamed to `ui-base--reset.scss` For the button for example it removes the firefox inner padding on buttons. Nobody will want to set the `kind` property to `base`, it would be unusable. 

For the default template we should also include a user-assigned class by default. `ui-button` already supports this, but it should be supported across all components.

``` hbs
<div class=":component {{classes.size}} {{classes.class}}">
  {{yield}}
</div>
```

**Comment by ianstarz** [comment]
@jacojoubert you should review https://github.com/prototypal-io/untitled-ui/pull/32 as well, and make sure things seem OK

**Comment by HeroicEric** [comment]
Closed by https://github.com/prototypal-io/untitled-ui/pull/50
