### ISSUE TITLE
Component to prevent page scroll

### ISSUE THREAD

**Issue by jacojoubert** [prototypal-io/untitled-ui#44]
It is sometimes necessary to prevent the user from scrolling the page to ensure a polished experience. this should be possible simply by dropping a down a component.
### Use Cases
- When a modal is open and you scroll the modal the page behind it will take overflow scrolling and it can be jarring. 
- Sometimes you want popups to feel native (`select`) and preventing page scroll enables that. It forces the user to interact with the popup before continuing.

**Comment by ebryn** [comment]
Implementation strategy:
- Anything but fixed positioning something on top :P

**Comment by miguelcobain** [comment]
I've done this in the past with a backdrop on body/some root element.

Using something like the usual

``` css
.backdrop {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
}
```

EDIT: this locked the scrolling in inner scrollable elements, not on `<body>`. Don't know if that affects this or not.
