### ISSUE TITLE
Class attribute classes should not be prefixed

### ISSUE THREAD

**Issue by jacojoubert** [prototypal-io/untitled-ui#52]
If a class is assigned using the class attribute like so `{{ui-component class="custom-class-name"}}` it should be outputted as is and not get turned into this `ui-component--custom-class-name`.

**Comment by ebryn** [comment]
This is a known issue with our template rewriter: https://github.com/prototypal-io/untitled-ui/issues/53

**Comment by ianstarz** [comment]
@ebryn @jacojoubert do we want to continue to whitelist/add exceptions to the rewriter? What is the reasoning behind this exception?

**Comment by ebryn** [comment]
Closing in favor of #53, let's discuss there if necessary
