### ISSUE TITLE
SCSS only component generation

### ISSUE THREAD

**Issue by HeroicEric** [prototypal-io/untitled-ui#90]
We're having an issue with the scss only kind components.
- We have a `ui-button` component and a `ui-button--default` kind
- We also have a `ui-button--primary` kind that is only defined by its scss file.
- We are generating an app component for the `ui-button--primary` component but that generated component is a reexport of the `ui-kind` component when it should be the `ui-button--default`.

I think I tracked the problem down to this case statement https://github.com/prototypal-io/untitled-ui/blob/master/lib/resolver.js#L35-L50

In the case where:

``` js
let themeComponent = 'modules/ui-base-theme/components/ui-button--primary.js';
let themeDefaultComponent = 'modules/ui-base-theme/components/ui-button--default.js';
let themeKindComponent = 'modules/ui-base-theme/components/ui-kind.js';
```

I think this should be resolving to the `themeDefaultComponent` but is currently resolving `themeKindComponent`.

I'm not sure where `context.js` comes from here https://github.com/prototypal-io/untitled-ui/blob/master/lib/resolver.js#L42-L44 but it doesn't seem to include the `themeDefaultComponent`.

**Comment by ianstarz** [comment]
It never goes into [this case](https://github.com/prototypal-io/untitled-ui/blob/master/lib/resolver.js#L42-L44) for `ui-button--primary`?

**Comment by HeroicEric** [comment]
@ianstarz It's matching the next one https://github.com/prototypal-io/untitled-ui/blob/master/lib/resolver.js#L45-L47

**Comment by ianstarz** [comment]
> I'm not sure where context.js comes from here https://github.com/prototypal-io/untitled-ui/blob/master/lib/resolver.js#L42-L44 but it doesn't seem to include the themeDefaultComponent.

@HeroicEric @ebryn this is correct, the js file does not exist. However, `ui-button--default.hbs` template exists. The current implementation doesn't take into account that a "baser" component has a template but not a js component file. Basically, we need to define requirements for this case.

**Comment by ianstarz** [comment]
Also, I'll need to start writing unit tests for the resolver to make sure we don't whack-a-mole, so feedback on #84 would be appreciated, as well.
